development:
  adapter: oracle_enhanced
  encoding: utf8
  reconnect: false
  host: 172.31.1.165
  database: bitest
  port: 1522
  pool: 20
  username: hdm
  password: hdm

production:
  adapter: oracle_enhanced
  encoding: utf8
  reconnect: false
  host: 172.31.1.165
  database: bitest
  port: 1522
  pool: 20
  username: hdm
  password: hdm
